# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

#[print_schema]
#file = "src/schema.rs"
#custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[print_schema]
file = "src/schema.rs"

[migrations_directory]
dir = "migrations"

#[migrations_directory]
#dir = "/home/andres/NC/NEWSOFT-COMPUTER/COURSES/course-rust/courses/rust-backend/courses/frameworks/actix/exercises/actix-api-diesel-postgres/migrations"
