
# ==== ROUTE ====


# ==== GETS ====

# Name: getusers
# Type: Service
# Route: /services/users/getusers
# Notes: Get all users
 GET http://localhost:8080/services/users/getusers


# ==== POSTS ====
# Name: postuser
# Type: Service
# Route: /services/users/postuser
# Notes: Create new user

# ==== PUTS ====

# ==== PATCH ====

# ==== DELETE ====




