

# Get all users
# GET https://reqres.in/api/users?page=2


# Get user
#GET https://reqres.in/api/users/2


# Create user
#POST https://reqres.in/api/users

#{
#    "name": "morpheus",
#    "job": "leader"
#}


# Update user
PUT https://reqres.in/api/users/2

{
    "name": "morpheus",
    "job": "zion resident"
}


# Delete user
