[package]
name = "http-mock"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
httpmock = "0.7.0"
reqwest = { version = "0.12.5", features = ["json"] }
serde = "1.0.204"
tokio = "1.39.2"
