
# ==== ROUTE ====


# ==== GETS ====

# Name: getusers
# Type: Service
# Route: /services/users/getusers
# Notes: Get all users
 GET http://localhost:8080/services/users/getusers


# ==== POSTS ====
# Name: postuser
# Type: Service
# Route: /services/users/postuser
# Notes: Create new user
POST http://localhost:8080/services/users/newuser
#POST {{URL}}/services/users/newuser
Content-Type: application/json
# Authorization: Bearer {{TOKEN}}

 {
    "first_name": "Marco",
    "last_name": "Giraldo Gomez",
    "email": "marcogiraldot21@gmail.com",
    "status": true
  }

# ==== PUTS ====

# ==== PATCH ====

# ==== DELETE ====




